---
- name: Install groups create
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _group.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_groups | default([]) }}"

- name: Install users create
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _user.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_users | default([]) }}"

- name: Install dirs create
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _dir.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_dirs | default([]) }}"

# add ansible.builtin.apt_repository and ansible.builtin.apt_key
# by list if no current version or force set
# ansible/roles/external/tenable/agent-install/tasks/install.yaml
- name: Install packages install
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _apt.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_pkgs | default([]) }}"
# remove repo and keys by list if was added

- name: Install templates upload
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _template.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_templates | default([]) }}"

- name: Install files upload
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _file.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_files | default([]) }}"

- name: Install rsync tree
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _rsync.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_rsync | default([]) }}"

- name: Install systemd units
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _systemd.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_systemd | default([]) }}"

- name: Install download files
  ansible.builtin.include_role:
    name: ansible-mega-var
    tasks_from: _download.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_downloads | default([]) }}"

- name: Install launch shell
  ansible.builtin.shell:
    chdir: "{{ i.chdir | default(omit) }}"
    cmd: "{{ i.cmd | default(omit) }}"
    creates: "{{ i.creates | default(omit) }}"
    executable: "{{ i.executable | default(omit) }}"
    free_form: "{{ i.free_form | default(omit) }}"
    removes: "{{ i.removes | default(omit) }}"
    stdin: "{{ i.stdin | default(omit) }}"
    stdin_add_newline: "{{ stdin_add_newline | default(omit) }}"
  changed_when: "i.changed_when | default(true)"
  check_mode: "{{ i.check_mode | default(omit) }}"
  loop_control:
    loop_var: i
  loop: "{{ mesv_shell | default([]) }}"
