---
- name: Call stop for each element
  ansible.builtin.include_tasks: _stop1.yaml
  loop_control:
    loop_var: i
  loop: "{{ mesv_install_service | default([]) + mesv_config_service | default([]) }}"
