---
- name: Tags block
  tags:
    - service-all
    - service-stop
    - service-start
    - service-reset
    - service-deploy
    - service-install
    - service-destroy
    - service-configure
  block:
    - name: Include corresponding tasks
      ansible.builtin.include_tasks: "_{{ file.name }}.yaml"
      when: "
        'all' in ansible_run_tags and skip_tags_list | intersect(file.tags) |
        length == 0 and ansible_run_tags | intersect(file.tags) | length > 0 or

        'all' in ansible_run_tags and ansible_run_tags | length > 1 and
        ansible_run_tags | intersect(file.tags) | length > 0 or

        'all' not in ansible_run_tags and ansible_run_tags | intersect(file.tags) |
        length > 0 and (mesv_service_tag is not defined or mesv_service_tag in
        ansible_run_tags)
        "
      loop_control:
        loop_var: file
      loop:
        - name: install
          tags:
            - all
            - service-all
            - service-deploy
            - service-install
        - name: configure
          tags:
            - all
            - service-all
            - service-deploy
            - service-configure
        - name: start
          tags:
            - all
            - service-all
            - service-start
        - name: stop
          tags:
            - service-stop
            - service-reset
        - name: destroy
          tags:
            - service-reset
            - service-destroy
