---
- name: Perform actions from inventory variables
  hosts: all
  vars:
    unit_name: gaiad
    regexp_line: '.+ committed state .+ height=\d{2,} .+'
  pre_tasks:
    - name: Create a check mode flag if running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: directory
        mode: "0644"
      check_mode: false
      when: ansible_check_mode
    - name: Remove the check mode flag if not running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: absent
      when: not ansible_check_mode
  tasks: []
