---
- name: Perform actions from inventory variables
  hosts: all
  pre_tasks:
    - name: Create a check mode flag if running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: directory
        mode: "0644"
      check_mode: false
      when: ansible_check_mode
      tags: [always]
    - name: Remove the check mode flag if not running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: absent
      when: not ansible_check_mode
      tags: [always]
  tasks:
    - name: Maintenance gaiad service with launcher
      ansible.builtin.include_role:
        name: ansible-mega-service
      vars:
        mesv_install_service: "{{ service_for_install }}"
      when: "prop_mode == 'none'"
      tags: [service-gaiad]

    - name: Maintenance gaiad service with systemd
      ansible.builtin.include_role:
        name: ansible-mega-service
      vars:
        # remove launcher key from dicts of list to maintain with plain systemd
        mesv_install_service: "{{ service_for_install | map('dict2items') |
          map('rejectattr', 'key', 'equalto', 'launcher') | map('items2dict') |
          map('combine', {'systemd': {'state': 'started'}}, recursive=True) |
          list }}"
      when: "prop_mode == 'systemd'"
      tags: [service-gaiad]

    - name: Check failure cases for stop manifests
      ansible.builtin.include_tasks:
        file: "includes/fail-test.yaml"
        apply:
          tags: [service-gaiad]
      when: "prop_mode.startswith('fail-')"
      tags: [service-gaiad]
