---
- name: Prepare controller
  hosts: localhost # DevSkim: ignore DS162092
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    roles_dir: "{{ lookup('env', 'HOME') }}/.ansible/roles"
  tasks:
    - name: Create molecule roles directory
      ansible.builtin.file:
        path: "{{ roles_dir }}"
        state: directory
        force: true
        recurse: true
    - name: Symbolic link to role
      ansible.builtin.file:
        src: /ansible
        dest: "{{ roles_dir }}/ansible-mega-service"
        state: link
        force: true

- name: Prepare targets
  hosts: all
  tasks: []
