---
- name: Block for failures
  block:
    - name: Maintenance gaiad service
      ansible.builtin.include_role:
        name: ansible-mega-service
  rescue:
    - name: Set fact to success converge
      ansible.builtin.set_fact:
        rescue_happened: true

- name: Check rescue happened
  when: "not rescue_happened | default(false)"
  ansible.builtin.fail:
    msg: Rescue isn't happened when [{{ prop_mode }}] should failure
